music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<pk>/', views.DetailView.as_view(), name="detail"),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls'))
]

music/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.artist + ' - ' + self.album_title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title + '.' + self.file_type

music/views.py
from django.views import generic
from .models import Album


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums';

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/details.html'

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>

    {#loads static files#}
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'music/style.css' %}" type="text/css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'music:index' %}" class="navbar-brand">Viberr</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;&nbsp;Albums
                    </a>
                </li>

                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;&nbsp;Songs
                    </a>
                </li>

                <form action="#" class="navbar-form navbar-left" role="search" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value=""/>
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;&nbsp;Add Album
                    </a>
                </li>

                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp;&nbsp;Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block body %}

{% endblock %}

</body>
</html>

music/templates/music/details.html
{% extends 'music/base.html' %}

{% block title %} Album Details {% endblock %}

{% block body %}
    <img src="{{ album.album_logo }}" alt="" style="width: 250px;height: 200px;">

    <h1>{{ album.album_title }}</h1>
    <h2>{{ album.artist }}</h2>

    {% for song in album.song_set.all %}
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png" alt=""/>
            {% endif %}
        </label>
        <br>
    {% endfor %}
{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
    <ul>
        {% for album in all_albums %}
            <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}